### ISSUE TITLE
Not pulling all the things

### ISSUE THREAD

**Issue by carolinehardin** [carolinehardin/learnProgrammingByForums#1] opened 2015-03-22 21:55 UTC
The Reddit scraper is not getting all the comments from reddit/r/learnprogramming .
See https://praw.readthedocs.org/en/v2.1.20/pages/comment_parsing.html
and http://www.reddit.com/dev/api
and #http://stackoverflow.com/questions/15078837/can-i-fetch-more-than-1000-images-with-the-reddit-api

**Comment by grantdobbe** [comment] 2015-03-23 01:51
I think the problem is confirmation bias. It's pulling close to 1000 results, but those results only contain about 200 links. Anyway, I cleaned up your code, added CSV output, and made it a little bit more user friendly.

Closing #1.

**Closed as completed by grantdobbe** 2015-03-23 01:51 UTC
